# Generated by Django 5.1.5 on 2026-08-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.clase', verbose_name='Clase'),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('clase', 'alumno', 'fecha'), name='asistencia_unica_por_clase_alumno_fecha'),
        ),
    ]
