# Generated by Django 5.1.5 on 2026-08-25 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(help_text='Formato 12345678-9', max_length=12, unique=True, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'Prefiere no informar')], default='N', max_length=1, verbose_name='Genero')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150, verbose_name='Contacto de emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Telefono de emergencia')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(choices=[('SALSA', 'Salsa'), ('BACHATA', 'Bachata'), ('REGGAETON', 'Reggaeton'), ('URBANO', 'Urbano'), ('TANGO', 'Tango'), ('KIDS', 'Kids Dance')], max_length=15, verbose_name='Estilo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('TODOS', 'Todos los niveles')], default='TODOS', max_length=12, verbose_name='Nivel')),
                ('dias_semana', models.CharField(help_text='Ej: Lunes y Miercoles', max_length=120, verbose_name='Dias de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de termino')),
                ('sala', models.CharField(default='Sala 1', max_length=50, verbose_name='Sala')),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=20, verbose_name='Cupo maximo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['nombre', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inscripcion')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto')),
                ('monto_clp', models.PositiveIntegerField(verbose_name='Monto (CLP)')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15, verbose_name='Metodo de pago')),
                ('pago_matricula', models.BooleanField(default=False, verbose_name='Es pago de matricula')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('ATRASADO', 'Atrasado')], default='PAGADO', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('precio_clp', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('duracion_dias', models.PositiveSmallIntegerField(default=30, verbose_name='Duracion (dias)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['precio_clp'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Se calcula automaticamente segun la duracion del plan.', verbose_name='Fecha de vencimiento')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
