# Generated by Django 5.1.5 on 2026-08-25 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_alumno', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesora',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor/a'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.clase', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='gestion.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='gestion.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='gestion.suscripcion', verbose_name='Suscripcion'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'clase'), name='inscripcion_unica_alumno_clase'),
        ),
    ]
