# Generated by Django 5.1.5 on 2026-08-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(choices=[('SALSA', 'Salsa'), ('BACHATA', 'Bachata'), ('REGGAETON', 'Reggaetón'), ('URBANO', 'Urbano'), ('TANGO', 'Tango'), ('KIDS', 'Kids Dance')], max_length=15, verbose_name='Estilo'),
        ),
    ]
