# Generated by Django 5.1.5 on 2026-08-27 00:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_clase_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('dias_anticipacion', models.PositiveSmallIntegerField(default=7, help_text='Con cuántos días de anticipación avisar un vencimiento.', verbose_name='Días de anticipación')),
                ('emails_destino', models.TextField(default='arealatina310@gmail.com', help_text='Separados por coma.', verbose_name='Emails que reciben el resumen')),
                ('hora_envio', models.TimeField(default='09:00', verbose_name='Hora de envío')),
                ('envio_activo', models.BooleanField(default=True, verbose_name='Enviar resumen por email')),
            ],
            options={
                'verbose_name': 'Configuración de alertas',
                'verbose_name_plural': 'Configuración de alertas',
            },
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='activa',
        ),
        migrations.AddField(
            model_name='alumno',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='relacion_emergencia',
            field=models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('PAREJA', 'Pareja'), ('AMIGO', 'Amigo/a'), ('OTRO', 'Otro')], default='OTRO', max_length=10, verbose_name='Relación'),
        ),
        migrations.AddField(
            model_name='clase',
            name='precio_clase_suelta',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Para cobrar esta clase por separado.', null=True, verbose_name='Precio clase suelta (CLP)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='detalle',
            field=models.CharField(blank=True, help_text='Obligatorio cuando el concepto es "Otro".', max_length=150, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='pago',
            name='nota_interna',
            field=models.TextField(blank=True, verbose_name='Nota interna'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de comprobante'),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(max_length=150, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero no indicar')], default='N', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(help_text='Formato 12.345.678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_emergencia',
            field=models.CharField(max_length=20, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo_maximo',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Cupo máximo'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dias_semana',
            field=models.CharField(help_text='Códigos separados por coma. Ej: LU,MI', max_length=30, verbose_name='Días de la semana'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nivel',
            field=models.CharField(choices=[('TODOS', 'Todos los niveles'), ('INICIAL', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='TODOS', max_length=12, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('MENSUALIDAD', 'Mensualidad'), ('MATRICULA', 'Matrícula'), ('CLASE_SUELTA', 'Clase suelta'), ('OTRO', 'Otro')], default='MENSUALIDAD', max_length=15, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago_matricula',
            field=models.BooleanField(default=False, verbose_name='Es pago de matrícula'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='gestion.suscripcion', verbose_name='Suscripción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion_dias',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Se calcula automáticamente según la duración del plan.', verbose_name='Fecha de vencimiento'),
        ),
        migrations.CreateModel(
            name='NotaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('texto', models.TextField(verbose_name='Nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.alumno', verbose_name='Alumno')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_escritas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Nota interna',
                'verbose_name_plural': 'Notas internas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('tipo', models.CharField(choices=[('VENCIMIENTO_PROXIMO', 'Plan por vencer'), ('PLAN_VENCIDO', 'Plan vencido'), ('PAGO_PENDIENTE', 'Pago pendiente')], max_length=20, verbose_name='Tipo')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje')),
                ('gestionada', models.BooleanField(default=False, verbose_name='Gestionada')),
                ('gestionada_en', models.DateTimeField(blank=True, null=True, verbose_name='Gestionada el')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gestion.alumno', verbose_name='Alumno')),
                ('gestionada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_gestionadas', to=settings.AUTH_USER_MODEL, verbose_name='Gestionada por')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='gestion.suscripcion', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['gestionada', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gestionada', False)), fields=('tipo', 'alumno'), name='alerta_unica_activa_por_tipo_alumno')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creó'), ('EDITAR', 'Editó'), ('ELIMINAR', 'Eliminó'), ('PAGO', 'Registró pago'), ('RENOVAR', 'Renovó plan'), ('ASISTENCIA', 'Registró asistencia'), ('LOGIN', 'Inició sesión')], max_length=12, verbose_name='Acción')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='gestion_aud_timesta_cb432a_idx'), models.Index(fields=['modelo', 'objeto_id'], name='gestion_aud_modelo_4f4329_idx')],
            },
        ),
    ]
