# Generated by Django 5.1.5 on 2026-08-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_dias_semana_a_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalertas',
            name='enviar_bienvenida',
            field=models.BooleanField(default=True, verbose_name='Correo de bienvenida al inscribir'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='enviar_recibos',
            field=models.BooleanField(default=True, verbose_name='Comprobante al registrar un pago'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='enviar_recordatorios',
            field=models.BooleanField(default=True, verbose_name='Aviso al alumno antes de que venza su plan'),
        ),
        migrations.AlterField(
            model_name='configuracionalertas',
            name='envio_activo',
            field=models.BooleanField(default=True, verbose_name='Enviar resumen diario al equipo'),
        ),
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('RECIBO', 'Comprobante de pago'), ('RECORDATORIO', 'Aviso de vencimiento'), ('RESUMEN', 'Resumen para el equipo'), ('CONTACTO', 'Mensaje del formulario web')], max_length=15, verbose_name='Tipo')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('asunto', models.CharField(max_length=250, verbose_name='Asunto')),
                ('referencia', models.CharField(blank=True, help_text='Identifica el envío para no repetirlo. Ej: RECORDATORIO-12-2026-08-30', max_length=60, verbose_name='Referencia')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos', to='gestion.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Correo enviado',
                'verbose_name_plural': 'Correos enviados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo', 'referencia'], name='gestion_cor_tipo_6e55d8_idx'), models.Index(fields=['-created_at'], name='gestion_cor_created_0c84e2_idx')],
            },
        ),
    ]
