# Generated by Django 5.1.5 on 2026-08-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_configuracionalertas_enviar_bienvenida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VENCIMIENTO_PROXIMO', 'Plan por vencer'), ('PLAN_VENCIDO', 'Plan vencido'), ('PAGO_PENDIENTE', 'Pago pendiente'), ('AUSENCIA', 'Lleva dos semanas sin venir')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='correoenviado',
            name='tipo',
            field=models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('RECIBO', 'Comprobante de pago'), ('RECORDATORIO', 'Aviso de vencimiento'), ('RESUMEN', 'Resumen para el equipo'), ('CONTACTO', 'Mensaje del formulario web'), ('REC_CLASE', 'Recordatorio de clase al alumno'), ('CONFIRMACION', 'Confirmacion de asistencia'), ('BIENV_PROFE', 'Bienvenida a profesora'), ('REC_PROFE', 'Recordatorio de clases a profesora'), ('CUMPLEANOS', 'Saludo de cumpleanos'), ('AUSENCIA', 'Aviso de ausencia prolongada'), ('INFORME', 'Informe mensual')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TokenActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('usado_en', models.DateTimeField(blank=True, null=True, verbose_name='Usado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_activacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de activación',
                'verbose_name_plural': 'Tokens de activación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la clase')),
                ('confirmado_en', models.DateTimeField(auto_now_add=True, verbose_name='Confirmado el')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='gestion.alumno', verbose_name='Alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='gestion.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Confirmación de asistencia',
                'verbose_name_plural': 'Confirmaciones de asistencia',
                'ordering': ['-fecha', '-confirmado_en'],
                'indexes': [models.Index(fields=['clase', 'fecha'], name='gestion_con_clase_i_5b6df2_idx')],
                'constraints': [models.UniqueConstraint(fields=('alumno', 'clase', 'fecha'), name='confirmacion_unica_alumno_clase_fecha')],
            },
        ),
    ]
