# Generated by Django 5.1.5 on 2026-08-29 03:24

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_alerta_tipo_alter_correoenviado_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=200, verbose_name='Archivo')),
                ('destino', models.CharField(blank=True, max_length=250, verbose_name='Destino')),
                ('tamano_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('estado', models.CharField(choices=[('OK', 'Correcto'), ('ERROR', 'Con error')], default='OK', max_length=6, verbose_name='Estado')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_emergencia',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_emergencia',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='notainterna',
            name='texto',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Nota'),
        ),
        migrations.CreateModel(
            name='BrechaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Detectada el')),
                ('descripcion', models.TextField(verbose_name='Qué pasó')),
                ('datos_afectados', models.TextField(help_text='Qué información quedó expuesta y de cuántas personas.', verbose_name='Datos afectados')),
                ('personas_afectadas', models.PositiveIntegerField(default=0, verbose_name='Personas afectadas')),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=8, verbose_name='Gravedad')),
                ('acciones_tomadas', models.TextField(blank=True, verbose_name='Acciones tomadas')),
                ('estado', models.CharField(choices=[('DETECTADA', 'Detectada'), ('INVESTIGACION', 'En investigación'), ('NOTIFICADA', 'Notificada a la autoridad'), ('CERRADA', 'Cerrada')], default='DETECTADA', max_length=14, verbose_name='Estado')),
                ('notificada_autoridad_en', models.DateTimeField(blank=True, null=True, verbose_name='Notificada a la autoridad el')),
                ('notificados_afectados', models.BooleanField(default=False, verbose_name='Se avisó a las personas afectadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Brecha de seguridad',
                'verbose_name_plural': 'Brechas de seguridad',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de caso')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('identificador', models.CharField(blank=True, help_text='Para poder encontrar sus datos en el sistema.', max_length=60, verbose_name='RUT o email registrado')),
                ('tipo', models.CharField(choices=[('ACCESO', 'Acceso a mis datos'), ('RECTIFICACION', 'Rectificación de datos'), ('CANCELACION', 'Cancelación (eliminación)'), ('OPOSICION', 'Oposición al tratamiento'), ('PORTABILIDAD', 'Portabilidad de datos')], max_length=15, verbose_name='Tipo de solicitud')),
                ('descripcion', models.TextField(verbose_name='Detalle de la solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta entregada')),
                ('cerrada_en', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada el')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibida el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['estado', 'created_at'],
            },
        ),
    ]
