# Generated by Django 5.1.5 on 2026-08-29 03:26

import apps.gestion.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_cifrar_datos_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='sospechoso',
            field=models.BooleanField(default=False, verbose_name='Marcado como sospechoso'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP. Máximo 5 MB.', null=True, upload_to='alumnos/', validators=[apps.gestion.validadores.validar_foto], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creó'), ('EDITAR', 'Editó'), ('ELIMINAR', 'Eliminó'), ('PAGO', 'Registró pago'), ('RENOVAR', 'Renovó plan'), ('ASISTENCIA', 'Registró asistencia'), ('LOGIN', 'Inició sesión'), ('LOGOUT', 'Cerró sesión'), ('LOGIN_FALLIDO', 'Intento fallido'), ('VER_FICHA', 'Consultó una ficha'), ('EXPORTAR', 'Descargó un reporte'), ('ARCO', 'Solicitud de datos personales')], max_length=15, verbose_name='Acción'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', '-timestamp'], name='gestion_aud_accion_59aaff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip', '-timestamp'], name='gestion_aud_ip_989f5b_idx'),
        ),
    ]
