# Generated by Django 5.1.5 on 2026-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auditlog_sospechoso_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoenviado',
            name='tipo',
            field=models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('RECIBO', 'Comprobante de pago'), ('RECORDATORIO', 'Aviso de vencimiento'), ('RESUMEN', 'Resumen para el equipo'), ('CONTACTO', 'Mensaje del formulario web'), ('REC_CLASE', 'Recordatorio de clase al alumno'), ('CONFIRMACION', 'Confirmacion de asistencia'), ('BIENV_PROFE', 'Bienvenida a profesora'), ('REC_PROFE', 'Recordatorio de clases a profesora'), ('CUMPLEANOS', 'Saludo de cumpleanos'), ('AUSENCIA', 'Aviso de ausencia prolongada'), ('INFORME', 'Informe mensual'), ('RESENA', 'Pedido de resena en Google')], max_length=15, verbose_name='Tipo'),
        ),
    ]
