# Generated by Django 5.1.5 on 2026-09-02 03:31

import apps.gestion.validadores
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_correoenviado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('bajada', models.CharField(blank=True, help_text='Una línea que resuma el área. Sale en la tarjeta del inicio.', max_length=140, verbose_name='Bajada')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='bi-stars', help_text='Nombre de un ícono de Bootstrap Icons. Ej: bi-music-note-beamed', max_length=40, verbose_name='Ícono')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', validators=[apps.gestion.validadores.validar_foto], verbose_name='Imagen')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('MUESTRA', 'Muestra'), ('TALLER', 'Taller'), ('COMPETENCIA', 'Competencia'), ('SOCIAL', 'Social o junta'), ('OTRO', 'Otro')], default='MUESTRA', max_length=12, verbose_name='Tipo')),
                ('resumen', models.CharField(blank=True, max_length=200, verbose_name='Resumen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('lugar', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', validators=[apps.gestion.validadores.validar_foto], verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace de inscripción')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('detalle', models.CharField(blank=True, help_text='Ej: Alumna de Bachata, Apoderado Kids & Teens.', max_length=80, verbose_name='Detalle')),
                ('texto', models.TextField(verbose_name='Testimonio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/', validators=[apps.gestion.validadores.validar_foto], verbose_name='Foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Para filtrar por edad en el buscador de horarios.', null=True, verbose_name='Edad mínima'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(choices=[('SALSA', 'Salsa'), ('BACHATA', 'Bachata'), ('REGGAETON', 'Reggaetón'), ('URBANO', 'Urbano'), ('HEELS', 'Heels'), ('TANGO', 'Tango'), ('KIDS', 'Kids Dance'), ('PILATES', 'Pilates Mat'), ('BARRE', 'Barre'), ('FLEXIBILIDAD', 'Flexibilidad'), ('REFORMER', 'Reformer')], max_length=15, verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='clase',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Decide en qué página del sitio aparece esta clase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gestion.categoria', verbose_name='Área'),
        ),
    ]
