# Generated by Django 5.1.5 on 2026-09-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_areas_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden', 'precio_clp'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Uno por línea. Salen como lista con check en el comparador.', verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='plan',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Se marca como “el más elegido” en el comparador del sitio.', verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='icono',
            field=models.CharField(default='bi-person', max_length=40, verbose_name='Ícono'),
        ),
        migrations.AddField(
            model_name='plan',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
