# Generated by Django 5.1.5 on 2026-09-04 23:26

import apps.gestion.validadores
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_plan_options_plan_beneficios_plan_destacado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('imagen', models.ImageField(upload_to='galeria/', validators=[apps.gestion.validadores.validar_foto], verbose_name='Imagen')),
                ('titulo', models.CharField(help_text='Describe la foto. Lo leen los buscadores y quien no puede ver la imagen.', max_length=100, verbose_name='Título')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Pilar', 'verbose_name_plural': 'Pilares'},
        ),
        migrations.AlterField(
            model_name='clase',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Baile Urbano o Bienestar. Decide bajo qué bloque sale esta clase en el sitio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gestion.categoria', verbose_name='Pilar'),
        ),
    ]
