# Generated by Django 5.1.5 on 2026-09-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_dos_pilares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('MUESTRA', 'Muestra'), ('TALLER', 'Taller'), ('COMPETENCIA', 'Competencia'), ('SOCIAL', 'Social o junta'), ('OTRO', 'Otro')], default='MUESTRA', max_length=12, verbose_name='Tipo')),
                ('resumen', models.CharField(blank=True, help_text='Una línea. Es lo que se lee en el inicio.', max_length=200, verbose_name='Resumen')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('lugar', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('enlace', models.URLField(blank=True, help_text='Opcional. Inscripción, entradas o el post de Instagram.', verbose_name='Enlace')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
