# Generated by Django 5.1.5 on 2026-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='detalle',
            field=models.TextField(blank=True, help_text='Para las alertas técnicas: el error exacto que devolvió el servidor.', verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='correoenviado',
            name='solo_consola',
            field=models.BooleanField(default=False, help_text='Se marca cuando el correo se imprimió en la terminal en vez de salir de verdad. Sirve para distinguir un envío real de una prueba de desarrollo.', verbose_name='Solo consola'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VENCIMIENTO_PROXIMO', 'Plan por vencer'), ('PLAN_VENCIDO', 'Plan vencido'), ('PAGO_PENDIENTE', 'Pago pendiente'), ('AUSENCIA', 'Lleva dos semanas sin venir'), ('CORREO_FALLIDO', 'Correo que no se pudo enviar')], max_length=20, verbose_name='Tipo'),
        ),
    ]
