# Generated by Django 5.1.5 on 2026-09-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alerta_detalle_correoenviado_solo_consola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gestion.alumno', verbose_name='Alumno'),
        ),
    ]
