# Generated by Django 5.1.5 on 2026-09-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_alerta_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='modalidad_pago',
            field=models.CharField(choices=[('SOLO_MENSUALIDAD', 'Solo por mensualidad'), ('SOLO_CLASE_SUELTA', 'Solo por clase suelta'), ('AMBAS', 'Mensualidad o clase suelta')], default='SOLO_MENSUALIDAD', help_text='Decide qué opciones se ofrecen al registrar un pago de esta clase.', max_length=20, verbose_name='Cómo se paga'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='precio_clase_suelta',
            field=models.PositiveIntegerField(blank=True, help_text='Solo si la clase admite pago suelto. Se usa para autocompletar el monto al cobrar.', null=True, verbose_name='Precio por clase suelta (CLP)'),
        ),
    ]
