# Generated by Django 5.1.5 on 2026-09-05 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_clase_modalidad_pago_alter_clase_precio_clase_suelta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoCondicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('version', models.CharField(help_text='Ej: 1.0, 2026-09. Se muestra en el correo de aceptación.', max_length=20, unique=True, verbose_name='Versión')),
                ('titulo', models.CharField(default='Términos y condiciones', max_length=150, verbose_name='Título')),
                ('texto', models.TextField(help_text='El documento completo. Es lo que la persona lee y acepta.', verbose_name='Texto')),
                ('enlace', models.URLField(blank=True, help_text='Opcional. Si el documento oficial vive en otra parte.', verbose_name='Enlace al documento')),
                ('fecha_vigencia', models.DateField(default=django.utils.timezone.localdate, help_text='Desde esta fecha se pide aceptar esta versión.', verbose_name='Vigente desde')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Término y condición',
                'verbose_name_plural': 'Términos y condiciones',
                'ordering': ['-fecha_vigencia', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AceptacionTerminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fecha_aceptacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aceptado el')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=250, verbose_name='Navegador')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceptaciones', to='gestion.alumno', verbose_name='Alumno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceptaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceptaciones', to='gestion.terminocondicion', verbose_name='Versión aceptada')),
            ],
            options={
                'verbose_name': 'Aceptación de términos',
                'verbose_name_plural': 'Aceptaciones de términos',
                'ordering': ['-fecha_aceptacion'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'termino'), name='una_aceptacion_por_version')],
            },
        ),
    ]
