# Generated by Django 5.1.5 on 2026-09-05 04:53

import apps.gestion.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_correoenviado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('emoji', models.CharField(blank=True, help_text='Opcional. Sale junto al nombre en el sitio y en el panel.', max_length=8, verbose_name='Emoji')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, help_text='Si se apaga, deja de aparecer en las sugerencias, pero las clases que ya la usan no cambian.', verbose_name='Sugerir al crear clases')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='clase',
            name='edad_minima',
        ),
        migrations.AddField(
            model_name='clase',
            name='publico',
            field=models.CharField(choices=[('TODAS', 'Cualquier edad'), ('KIDS', 'Kids & Teens')], default='TODAS', help_text='Dos opciones y nada más: o es para niños y adolescentes, o entra cualquiera.', max_length=10, verbose_name='Para quién es'),
        ),
        migrations.AddField(
            model_name='pago',
            name='boleta',
            field=models.FileField(blank=True, help_text='PDF o imagen. Queda guardada en la ficha del alumno.', null=True, upload_to='boletas/%Y/%m/', validators=[apps.gestion.validadores.validar_documento], verbose_name='Boleta o comprobante'),
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_incluidas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas clases distintas cubre el plan. Déjalo vacío si es ilimitado (pase libre). Se usa para avisar cuando el alumno marca más clases de las que el plan cubre.', null=True, verbose_name='Clases que incluye'),
        ),
        migrations.AddField(
            model_name='plan',
            name='pilares',
            field=models.ManyToManyField(blank=True, help_text='Déjalo vacío para que sirva en todo el estudio. Marca los dos si el plan permite combinar baile y bienestar.', related_name='planes', to='gestion.categoria', verbose_name='Pilares que cubre'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Disciplina'),
        ),
    ]
