# Generated by Django 5.1.5 on 2026-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_catalogo_disciplinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('visitas_estimadas', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('formularios_contacto_enviados', models.PositiveIntegerField(default=0, verbose_name='Formularios de contacto')),
            ],
            options={
                'verbose_name': 'Estadística diaria',
                'verbose_name_plural': 'Estadísticas diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='enviar_resumen_semanal',
            field=models.BooleanField(default=True, verbose_name='Enviar resumen semanal los lunes'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='meta_mensual_clp',
            field=models.PositiveIntegerField(default=0, help_text='En pesos. Cuando los ingresos del mes la superan, se genera una alerta de negocio. En 0 no se revisa.', verbose_name='Meta mensual de ingresos'),
        ),
        migrations.CreateModel(
            name='AlertaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVO_ALUMNO', 'Alumno nuevo'), ('META_MENSUAL', 'Meta mensual alcanzada'), ('CAIDA_INSCRIPCIONES', 'Caída de inscripciones'), ('AUSENTE', 'Alumno ausente hace tiempo'), ('PAGO_CRITICO', 'Pago muy atrasado')], max_length=20, verbose_name='Tipo')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje')),
                ('datos_json', models.JSONField(blank=True, default=dict, verbose_name='Datos')),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('ATENCION', 'Requiere atención'), ('URGENTE', 'Urgente')], default='INFO', max_length=10, verbose_name='Severidad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Alerta de negocio',
                'verbose_name_plural': 'Alertas de negocio',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['-creada_en'], name='gestion_ale_creada__e4f7f5_idx'), models.Index(fields=['leida', '-creada_en'], name='gestion_ale_leida_f6e5d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRAFICO_PICO', 'Pico de tráfico'), ('TRAFICO_CAIDA', 'Caída de tráfico'), ('ERROR_SERVIDOR', 'Error del servidor'), ('SEGURIDAD', 'Seguridad')], max_length=20, verbose_name='Tipo')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('datos_json', models.JSONField(blank=True, default=dict, verbose_name='Datos')),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('ATENCION', 'Requiere atención'), ('URGENTE', 'Urgente')], default='INFO', max_length=10, verbose_name='Severidad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Alerta de sistema',
                'verbose_name_plural': 'Alertas de sistema',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['-creada_en'], name='gestion_ale_creada__e645e0_idx')],
            },
        ),
    ]
