# Generated by Django 5.1.5 on 2026-08-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Solo para profesores. Ej: Salsa y Bachata', max_length=120, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super administrador'), ('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor/a'), ('ALUMNO', 'Alumno/a')], default='ALUMNO', max_length=12, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
