# Generated by Django 5.1.5 on 2026-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_especialidad_alter_customuser_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correo_institucional',
            field=models.EmailField(blank=True, help_text='Se genera solo al crear la profesora. Es con lo que entra al sistema.', max_length=254, null=True, unique=True, verbose_name='Correo del estudio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='correo_personal',
            field=models.EmailField(blank=True, help_text='Acá le llegan la clave temporal y los avisos. Tiene que ser un correo que la persona revise de verdad.', max_length=254, verbose_name='Correo personal'),
        ),
    ]
