# Generated by Django 5.1.5 on 2026-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_correos_profesoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, help_text='Se enciende solo al generarle una clave temporal.', verbose_name='Debe cambiar la contraseña'),
        ),
    ]
